on:
  push:
    branches:
      - 'feature/**' # match an pushes on feature/* and feature/<any sub branch>/*
      - main
    paths-ignore: # dont run when changes made to these folders
      - '.vscode/**'

jobs:
  cicd:
    name: cicd
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: fetch all history and tags from all branches for gitversion
        run: git fetch --prune --unshallow

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: execute gitversion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.6

      - name: print gitversion
        run: |
          # echo "Major: ${{ steps.gitversion.outputs.major }}"
          # echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          # echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          # echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
          # echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: clean install dependencies
        run: npm ci

      - name: update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: '${{github.workspace}}/package.json'
          patch-syntax: |
            = /version => "${{ steps.gitversion.outputs.semVer }}"
            = /displayName => "vc65x"
            = /description => "VC65X - A 65XX Development Environment."

      - name: add version in CHANGELOG.md
        uses: cschleiden/replace-tokens@v1
        with:
          files: '${{github.workspace}}/CHANGELOG.md'
        env:
          VERSION: "${{ steps.gitversion.outputs.semVer }}"

      - name: compile and create vsix
        run: npm run package

      - name: print vsix path
        run: |
          # echo "VSIX Path: ${{ env.vsix_path }}"

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v2
        with:
          name: vsix-viewer-${{steps.gitversion.outputs.semVer}}.vsix
          path: ${{github.workspace}}/vsix-viewer-${{steps.gitversion.outputs.semVer}}.vsix